### ISSUE TITLE
Traverse2 doesn't work on static members

### ISSUE THREAD

**Issue by jzebedee** [BUTR/Harmony.Extensions#67]
The guard clauses in Traverse2's SetValue implementation will exit on a null `_root`, which makes Field or Property writes to static members a no-op. The same code succeeds in the original Harmony implementation.

Broken (field will not be changed):
`Traverse2.Create(typeof(MBSaveLoad)).Field<ISaveDriver>("_saveDriver").Value = null`

Works:
`Traverse.Create(typeof(MBSaveLoad)).Field<ISaveDriver>("_saveDriver").Value = null`

**Comment by Aragas** [comment]
Should be fixed with Harmony.Extensions `3.1.0.68`
